### ISSUE TITLE
版权声明

### ISSUE THREAD

**Issue by BangBOOM** [haomingdouranggouqil/Ancient-Chinese-Modern-Chinese-translate#1]
使用了我用GPL开源的[古文现代文平行语料库](https://github.com/BangBOOM/Classical-Chinese)，请标注来源并修改你的开源协议，而不是直接复制放到你的仓库。

**Comment by haomingdouranggouqil** [comment]
您好，首先要向您表示道歉，这个项目我暂时还没开始做，只是做了数据集之类的先期准备，还没来得及写代码与readme文件，自然也尚未标注数据集来源于您的项目。
现在我已经修改了readme文件，将数据集来源添加了上去，至于开源协议，我也修改为GPLv3.0。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haomingdouranggouqil/Ancient-Chinese-Modern-Chinese-translate"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月1日(星期二) 晚上7:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[haomingdouranggouqil/Ancient-Chinese-Modern-Chinese-translate] 版权声明 (#1)





 
使用了我用GPL开源的数据集，请标注来源并修改你的开源协议，而不是直接复制放到你的仓库。

**Comment by BangBOOM** [comment]
好的，只是想强调一下版权意识。

haomingdouranggouqil ***@***.***>于2021年6月1日 周二20:13写道：
